from __future__ import annotations

from pathlib import Path
from typing import Any

from assured_downstream.overlay_render import RenderResult, normalize_pin_map, require_pins


def render_release_workflow(
    profile: dict[str, Any],
    *,
    root: Path,
    pins: dict[str, Any],
    execute: bool = False,
    force: bool = False,
) -> RenderResult:
    root = root.resolve()
    if not root.exists():
        raise FileNotFoundError(root)
    if not root.is_dir():
        raise NotADirectoryError(root)

    release = profile.get("release") or {}
    required = require_pins(
        normalize_pin_map(pins),
        release.get("required_actions") or [],
    )
    if required is None:
        return RenderResult(
            written=[],
            skipped=[
                {
                    "id": "attested-release-workflow",
                    "reason": "release workflow rendering requires full SHA pins for all required actions",
                }
            ],
        )

    relative_path = release.get("workflow_path") or ".github/workflows/saucetotal-attested-release.yml"
    target = root / relative_path
    if target.exists() and not force:
        return RenderResult(
            written=[],
            skipped=[
                {
                    "id": "attested-release-workflow",
                    "reason": f"{relative_path} already exists; pass --force to overwrite",
                }
            ],
        )

    content = attested_release_workflow(profile, required)
    if execute:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    return RenderResult(
        written=[{"id": "attested-release-workflow", "path": relative_path}],
        skipped=[],
    )


def attested_release_workflow(profile: dict[str, Any], pins: dict[str, str]) -> str:
    release = profile["release"]
    artifact_paths = release["artifact_paths"]
    sbom_path = release["sbom_path"]
    build_commands = release["build_commands"]

    return f"""# Generated by SauceTotal. Review before merging upstream.
# Status: {profile.get('status', 'draft-human-review-required')}
name: SauceTotal Attested Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'secure-v*'

permissions:
  contents: read
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build-attest:
    runs-on: {release.get('runs_on', 'ubuntu-latest')}
    steps:
      - uses: actions/checkout@{pins['actions/checkout']}

      - name: Build release artifacts
        run: |
{indent_commands(build_commands, 10)}

      - name: Generate SBOM
        uses: anchore/sbom-action@{pins['anchore/sbom-action']}
        with:
          path: .
          format: {release.get('sbom_format', 'spdx-json')}
          output-file: {sbom_path}
          upload-artifact: "false"
          upload-release-assets: "false"

      - name: Attest build provenance
        uses: actions/attest@{pins['actions/attest']}
        with:
          subject-path: |
{indent_commands(artifact_paths, 12)}

      - name: Attest SBOM
        uses: actions/attest@{pins['actions/attest']}
        with:
          subject-path: |
{indent_commands(artifact_paths, 12)}
          sbom-path: {sbom_path}

      - name: Upload release evidence
        uses: actions/upload-artifact@{pins['actions/upload-artifact']}
        with:
          name: saucetotal-release-evidence
          path: |
{indent_commands(artifact_paths + [sbom_path], 12)}
          if-no-files-found: error
"""


def indent_commands(lines: list[str], spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" for line in lines)

