from __future__ import annotations

import errno
import json
import os
import re
import shlex
import uuid
from pathlib import Path, PurePosixPath
from typing import Any

from assured_downstream.overlay_render import (
    RenderResult,
    normalize_pin_map,
    require_pins,
)


ASSURED_DOWNSTREAM_PREDICATE_TYPE = (
    "https://assured-downstream.dev/attestation/release/v1"
)
BUILDER_IMAGE_PATTERN = re.compile(r"^[a-z0-9][a-z0-9._/-]*$")
BUILDER_DIGEST_PATTERN = re.compile(r"^[0-9a-f]{64}$")
RUN_AS_PATTERN = re.compile(r"^[0-9]+:[0-9]+$")
REPOSITORY_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
RUNNER_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
TAG_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/*?-]*$")
ARTIFACT_PATTERN = re.compile(r"^[A-Za-z0-9._/*?+-]+$")
FILE_PATH_PATTERN = re.compile(r"^[A-Za-z0-9._/+-]+$")
TEMPLATE_ACTIONS = {
    "actions/checkout",
    "actions/attest",
    "actions/download-artifact",
    "actions/upload-artifact",
    "anchore/sbom-action",
}


def render_release_workflow(
    profile: dict[str, Any],
    *,
    root: Path,
    pins: dict[str, Any],
    execute: bool = False,
    force: bool = False,
) -> RenderResult:
    root = root.resolve()
    if not root.exists():
        raise FileNotFoundError(root)
    if not root.is_dir():
        raise NotADirectoryError(root)

    release = validate_release_profile(profile)
    required = require_pins(
        normalize_pin_map(pins),
        release.get("required_actions") or [],
    )
    if required is None:
        return RenderResult(
            written=[],
            skipped=[
                {
                    "id": "attested-release-workflow",
                    "reason": "release workflow rendering requires full SHA pins for all required actions",
                }
            ],
        )

    relative_path = release["workflow_path"]
    target = root / relative_path
    resolved_target = target.resolve()
    if not resolved_target.is_relative_to(root):
        raise ValueError("Release workflow path escapes the repository root")
    for parent in (target, *target.parents):
        if parent == root.parent:
            break
        if parent.exists() and parent.is_symlink():
            raise ValueError("Release workflow path traverses a symlink")
    if target.exists() and not force:
        return RenderResult(
            written=[],
            skipped=[
                {
                    "id": "attested-release-workflow",
                    "reason": f"{relative_path} already exists; pass --force to overwrite",
                }
            ],
        )

    content = attested_release_workflow(profile, required)
    if execute:
        try:
            write_text_confined(
                root,
                relative_path,
                content,
                force=force,
            )
        except FileExistsError:
            return RenderResult(
                written=[],
                skipped=[
                    {
                        "id": "attested-release-workflow",
                        "reason": f"{relative_path} appeared during rendering; retry with --force to overwrite",
                    }
                ],
            )

    return RenderResult(
        written=[{"id": "attested-release-workflow", "path": relative_path}],
        skipped=[],
    )


def attested_release_workflow(profile: dict[str, Any], pins: dict[str, str]) -> str:
    release = validate_release_profile(profile)
    artifact_paths = release["artifact_paths"]
    sbom_path = release["sbom_path"]
    build_commands = isolated_build_commands(profile)
    lineage_commands = lineage_verification_commands(profile)
    tag_trigger = release_tag_trigger(profile)
    lineage = profile.get("lineage") or {}
    source_repository = lineage.get("source_full_name") or "UNCONFIRMED"
    upstream_ref = lineage.get("upstream_ref") or "UNCONFIRMED"

    return f"""# Generated by Assured Downstream. Review before merging upstream.
# Status: {profile.get("status", "draft-human-review-required")}
name: Assured Downstream Attested Release

on:
  workflow_dispatch:
{tag_trigger}

permissions:
  contents: read

jobs:
  build:
    runs-on: {release.get("runs_on", "ubuntu-latest")}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@{pins["actions/checkout"]}
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Verify source lineage
        env:
          SOURCE_REPOSITORY: {json.dumps(source_repository)}
          UPSTREAM_REF: {json.dumps(upstream_ref)}
        run: |
{indent_commands(lineage_commands, 10)}

      - name: Build release artifacts
        run: |
{indent_commands(build_commands, 10)}

      - name: Upload isolated build outputs
        uses: actions/upload-artifact@{pins["actions/upload-artifact"]}
        with:
          name: assured-downstream-build-output
          path: |
{indent_commands(artifact_paths, 12)}
          if-no-files-found: error
          retention-days: 1

  inspect-evidence:
    needs: build
    runs-on: {release.get("runs_on", "ubuntu-latest")}
    permissions: {{}}
    steps:
      - name: Download isolated build outputs
        uses: actions/download-artifact@{pins["actions/download-artifact"]}
        with:
          name: assured-downstream-build-output
          path: assured-input/artifacts

      - name: Validate build output boundary
        run: |
{indent_text(artifact_validation_script(), 10)}

      - name: Generate SBOM
        uses: anchore/sbom-action@{pins["anchore/sbom-action"]}
        with:
          path: assured-input/artifacts
          format: {release.get("sbom_format", "spdx-json")}
          output-file: {sbom_path}
          upload-artifact: "false"
          upload-release-assets: "false"

      - name: Verify SBOM generation did not alter build outputs
        run: |
{indent_text(artifact_inventory_verification_script(), 10)}

      - name: Upload inspected evidence inputs
        uses: actions/upload-artifact@{pins["actions/upload-artifact"]}
        with:
          name: assured-downstream-inspected-evidence
          path: |
            assured-input/artifacts
            assured-evidence/artifact-inventory.json
            {sbom_path}
          if-no-files-found: error
          retention-days: 1

  attest-evidence:
    needs: inspect-evidence
    runs-on: {release.get("runs_on", "ubuntu-latest")}
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Download inspected evidence inputs
        uses: actions/download-artifact@{pins["actions/download-artifact"]}
        with:
          name: assured-downstream-inspected-evidence
          path: .

      - name: Attest build provenance
        id: provenance
        uses: actions/attest@{pins["actions/attest"]}
        with:
          subject-path: assured-input/artifacts/**/*

      - name: Attest SBOM
        id: sbom
        uses: actions/attest@{pins["actions/attest"]}
        with:
          subject-path: assured-input/artifacts/**/*
          sbom-path: {sbom_path}

      - name: Attest Assured Downstream policy
        id: assured_downstream
        uses: actions/attest@{pins["actions/attest"]}
        with:
          subject-path: assured-input/artifacts/**/*
          predicate-type: {ASSURED_DOWNSTREAM_PREDICATE_TYPE}
          predicate: |
            {{
              "policyVersion": "assured-downstream-attested-v1",
              "sourceRepository": {json.dumps(source_repository)},
              "targetRepository": "${{{{ github.repository }}}}",
              "upstreamRef": {json.dumps(upstream_ref)},
              "overlayRef": "${{{{ github.sha }}}}",
              "workflowRef": "${{{{ github.workflow_ref }}}}",
              "lineagePolicy": "upstream ref is an ancestor of the attested overlay ref"
            }}

      - name: Stage signed attestation bundles
        env:
          PROVENANCE_BUNDLE: ${{{{ steps.provenance.outputs['bundle-path'] }}}}
          SBOM_BUNDLE: ${{{{ steps.sbom.outputs['bundle-path'] }}}}
          POLICY_BUNDLE: ${{{{ steps.assured_downstream.outputs['bundle-path'] }}}}
        run: |
          set -eu
          mkdir -p assured-evidence/attestations
          test -f "$PROVENANCE_BUNDLE"
          test -f "$SBOM_BUNDLE"
          test -f "$POLICY_BUNDLE"
          cp -- "$PROVENANCE_BUNDLE" assured-evidence/attestations/provenance.sigstore.json
          cp -- "$SBOM_BUNDLE" assured-evidence/attestations/sbom.sigstore.json
          cp -- "$POLICY_BUNDLE" assured-evidence/attestations/policy.sigstore.json

      - name: Generate portable evidence manifest and guide
        env:
          SOURCE_FULL_NAME: {json.dumps(source_repository)}
          TARGET_FULL_NAME: ${{{{ github.repository }}}}
          UPSTREAM_REF: {json.dumps(upstream_ref)}
          OVERLAY_REF: ${{{{ github.sha }}}}
          RELEASE_TAG: ${{{{ github.ref_name }}}}
        run: |
{indent_text(evidence_assembly_script(sbom_path), 10)}

      - name: Upload release evidence
        uses: actions/upload-artifact@{pins["actions/upload-artifact"]}
        with:
          name: assured-downstream-release-evidence
          path: |
            assured-input/artifacts
            assured-evidence
            evidence.json
            VERIFY.md
          if-no-files-found: error
"""


def artifact_validation_script() -> str:
    return """python - <<'PY'
import hashlib
import json
from pathlib import Path

root = Path("assured-input/artifacts").resolve()
output = Path("assured-evidence")
output.mkdir(parents=True, exist_ok=True)
max_files = 1024
max_file_bytes = 1024 * 1024 * 1024
max_total_bytes = 5 * 1024 * 1024 * 1024

def digest_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()

files = []
total_size = 0
for path in sorted(root.rglob("*")):
    if path.is_symlink():
        raise SystemExit(f"symlink build output is forbidden: {path}")
    if not path.is_file():
        continue
    resolved = path.resolve()
    if not resolved.is_relative_to(root):
        raise SystemExit(f"build output escaped artifact root: {path}")
    stat = path.stat()
    if stat.st_nlink != 1:
        raise SystemExit(f"hard-linked build output is forbidden: {path}")
    relative = path.relative_to(Path.cwd()).as_posix()
    if "\\\\" in relative or any(ord(character) < 32 or ord(character) == 127 for character in relative):
        raise SystemExit(f"non-portable build output path is forbidden: {path}")
    if stat.st_size > max_file_bytes:
        raise SystemExit(f"build output exceeds per-file size limit: {path}")
    total_size += stat.st_size
    if total_size > max_total_bytes:
        raise SystemExit("build outputs exceed total size limit")
    files.append({
        "path": relative,
        "size": stat.st_size,
        "sha256": digest_file(path),
    })
if not files:
    raise SystemExit("isolated build produced no regular artifacts")
if len(files) > max_files:
    raise SystemExit("isolated build produced too many artifacts")
(output / "artifact-inventory.json").write_text(
    json.dumps({"schema_version": 1, "artifacts": files}, indent=2, sort_keys=True) + "\\n",
    encoding="utf-8",
)
PY"""


def artifact_inventory_verification_script() -> str:
    return """python - <<'PY'
import hashlib
import json
from pathlib import Path

root = Path("assured-input/artifacts").resolve()
inventory_path = Path("assured-evidence/artifact-inventory.json")

def digest_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()

inventory = json.loads(inventory_path.read_text(encoding="utf-8"))
if inventory.get("schema_version") != 1 or not isinstance(inventory.get("artifacts"), list):
    raise SystemExit("artifact inventory is invalid")
expected = {item.get("path"): item for item in inventory["artifacts"] if isinstance(item, dict)}
if len(expected) != len(inventory["artifacts"]):
    raise SystemExit("artifact inventory contains invalid or duplicate entries")

actual = {}
for path in sorted(root.rglob("*")):
    if path.is_symlink():
        raise SystemExit(f"symlink build output is forbidden: {path}")
    if not path.is_file():
        continue
    stat = path.stat()
    if stat.st_nlink != 1:
        raise SystemExit(f"hard-linked build output is forbidden: {path}")
    relative = path.relative_to(Path.cwd()).as_posix()
    actual[relative] = {
        "path": relative,
        "size": stat.st_size,
        "sha256": digest_file(path),
    }
if actual != expected:
    raise SystemExit("build outputs changed after boundary validation")
PY"""


def evidence_assembly_script(sbom_path: str) -> str:
    return f"""python - <<'PY'
import hashlib
import json
import os
import shlex
from datetime import datetime, timezone
from pathlib import Path

cwd = Path.cwd().resolve()

def digest_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()

def entry(path, role):
    candidate = Path(path)
    if candidate.is_symlink():
        raise SystemExit(f"symlink {{role}} evidence is forbidden: {{candidate}}")
    path = candidate.resolve()
    if not path.is_file() or not path.is_relative_to(cwd):
        raise SystemExit(f"invalid {{role}} evidence path: {{candidate}}")
    stat = path.stat()
    if stat.st_nlink != 1:
        raise SystemExit(f"hard-linked {{role}} evidence is forbidden: {{candidate}}")
    relative = path.relative_to(cwd).as_posix()
    return {{
        "role": role,
        "path": relative,
        "name": path.name,
        "size": stat.st_size,
        "sha256": digest_file(path),
    }}

artifacts = [entry(path, "artifacts") for path in sorted(Path("assured-input/artifacts").rglob("*")) if path.is_file()]
sboms = [entry({json.dumps(sbom_path)}, "sboms")]
attestations = [entry(path, "attestations") for path in sorted(Path("assured-evidence/attestations").glob("*.json"))]
reports = [entry("assured-evidence/artifact-inventory.json", "reports")]
if not artifacts or not sboms or len(attestations) != 3:
    raise SystemExit("evidence bundle is incomplete")

inventory = json.loads(Path(reports[0]["path"]).read_text(encoding="utf-8"))
inventory_artifacts = inventory.get("artifacts", [])
expected_artifacts = {{item.get("path"): item for item in inventory_artifacts if isinstance(item, dict)}}
actual_artifacts = {{item["path"]: {{key: item[key] for key in ("path", "size", "sha256")}} for item in artifacts}}
if (
    inventory.get("schema_version") != 1
    or not isinstance(inventory_artifacts, list)
    or len(expected_artifacts) != len(inventory_artifacts)
    or expected_artifacts != actual_artifacts
):
    raise SystemExit("inspected artifact inventory does not match attestation subjects")

manifest = {{
    "schema_version": 1,
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "project": {{
        "source_full_name": os.environ["SOURCE_FULL_NAME"],
        "target_full_name": os.environ["TARGET_FULL_NAME"],
        "upstream_ref": os.environ["UPSTREAM_REF"],
        "overlay_ref": os.environ["OVERLAY_REF"],
        "release_tag": os.environ["RELEASE_TAG"],
        "assurance": "Evidence-candidate",
    }},
    "evidence": {{
        "artifacts": artifacts,
        "sboms": sboms,
        "attestations": attestations,
        "traces": [],
        "reports": reports,
    }},
}}
manifest_path = Path("evidence.json")
manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\\n", encoding="utf-8")

guide = [
    "# Assured Downstream Verification Guide",
    "",
    "Status: candidate evidence. Attested promotion requires independent bundle verification.",
    "",
    "## Local digest checks",
    "",
    "```bash",
]
for role_entries in manifest["evidence"].values():
    for item in role_entries:
        guide.append("printf '%s  %s\\n' " + shlex.quote(item["sha256"]) + " " + shlex.quote(item["path"]) + " | shasum -a 256 -c -")
guide.extend([
    "```",
    "",
    "## Sigstore verification",
    "",
    "```bash",
])
for item in artifacts:
    guide.append("gh attestation verify " + shlex.quote(item["path"]) + " -R " + shlex.quote(os.environ["TARGET_FULL_NAME"]))
guide.extend([
    "```",
    "",
    "This bundle does not claim reproducibility, syscall completeness, or semantic safety.",
    "",
])
Path("VERIFY.md").write_text("\\n".join(guide), encoding="utf-8")
PY"""


def validate_release_profile(profile: dict[str, Any]) -> dict[str, Any]:
    release = profile.get("release")
    if not isinstance(release, dict):
        raise ValueError("Release profile has no release configuration")

    require_safe_path(
        release.get("workflow_path"),
        label="release workflow",
        prefix=(".github", "workflows"),
        pattern=FILE_PATH_PATTERN,
        suffixes=(".yml", ".yaml"),
    )
    require_safe_path(
        release.get("sbom_path"),
        label="SBOM output",
        prefix=("assured-evidence",),
        pattern=FILE_PATH_PATTERN,
    )
    artifact_paths = release.get("artifact_paths")
    if not isinstance(artifact_paths, list) or not artifact_paths:
        raise ValueError("Release artifact paths must be a non-empty list")
    for artifact_path in artifact_paths:
        require_safe_path(
            artifact_path,
            label="release artifact",
            prefix=("dist",),
            pattern=ARTIFACT_PATTERN,
        )
    require_pattern(release.get("runs_on"), RUNNER_PATTERN, label="runner")
    require_pattern(
        release.get("confirmed_tag_pattern"),
        TAG_PATTERN,
        label="release tag pattern",
    )
    if release.get("sbom_format") != "spdx-json":
        raise ValueError("Release SBOM format must be spdx-json")
    required_actions = release.get("required_actions")
    if (
        not isinstance(required_actions, list)
        or not all(isinstance(action, str) for action in required_actions)
        or not TEMPLATE_ACTIONS.issubset(set(required_actions))
    ):
        raise ValueError("Release profile omits a required pinned action")
    return release


def require_safe_path(
    value: Any,
    *,
    label: str,
    prefix: tuple[str, ...],
    pattern: re.Pattern[str],
    suffixes: tuple[str, ...] | None = None,
) -> str:
    if not isinstance(value, str) or pattern.fullmatch(value) is None:
        raise ValueError(f"{label.capitalize()} path contains unsafe characters")
    path = PurePosixPath(value)
    if path.is_absolute() or not path.parts or ".." in path.parts:
        raise ValueError(f"{label.capitalize()} path escapes its allowed root")
    if path.parts[: len(prefix)] != prefix:
        raise ValueError(
            f"{label.capitalize()} path must start with {'/'.join(prefix)}"
        )
    if suffixes is not None and not value.endswith(suffixes):
        raise ValueError(f"{label.capitalize()} path has an unsupported extension")
    return value


def require_pattern(value: Any, pattern: re.Pattern[str], *, label: str) -> str:
    if not isinstance(value, str) or pattern.fullmatch(value) is None:
        raise ValueError(f"{label.capitalize()} contains unsafe characters")
    return value


def release_tag_trigger(profile: dict[str, Any]) -> str:
    if not release_profile_confirmed(profile):
        return ""
    release = profile.get("release") or {}
    pattern = release.get("confirmed_tag_pattern") or "secure-v*"
    return f"""  push:
    tags:
      - '{pattern}'"""


def release_profile_confirmed(profile: dict[str, Any]) -> bool:
    review = profile.get("review") or {}
    return bool(
        review.get("release_workflow_confirmed") is True
        and review.get("artifact_paths_confirmed") is True
        and review.get("isolated_builder_confirmed") is True
        and review.get("lineage_confirmed") is True
        and lineage_is_valid(profile.get("lineage"))
    )


def lineage_verification_commands(profile: dict[str, Any]) -> list[str]:
    if not release_profile_confirmed(profile):
        return [
            "echo 'source lineage is not fully confirmed; refusing to fetch or build' >&2",
            "exit 1",
        ]
    return [
        "set -eu",
        'git fetch --no-tags --depth=1 "https://github.com/${SOURCE_REPOSITORY}.git" "$UPSTREAM_REF"',
        'test "$(git rev-parse FETCH_HEAD)" = "$UPSTREAM_REF"',
        'git merge-base --is-ancestor "$UPSTREAM_REF" "$GITHUB_SHA"',
    ]


def isolated_build_commands(profile: dict[str, Any]) -> list[str]:
    release = profile.get("release") or {}
    builder = release.get("isolated_builder") or {}
    review = profile.get("review") or {}
    if review.get("isolated_builder_confirmed") is not True:
        return [
            "echo 'isolated builder is not confirmed; refusing to execute upstream code' >&2",
            "exit 1",
        ]
    if not release_profile_confirmed(profile):
        return [
            "echo 'release profile or source lineage is not fully confirmed; refusing to execute upstream code' >&2",
            "exit 1",
        ]
    image = builder.get("image")
    digest = builder.get("image_digest")
    run_as = builder.get("run_as")
    argv = builder.get("command_argv")
    if (
        not isinstance(image, str)
        or BUILDER_IMAGE_PATTERN.fullmatch(image) is None
        or not isinstance(digest, str)
        or BUILDER_DIGEST_PATTERN.fullmatch(digest) is None
        or not isinstance(run_as, str)
        or RUN_AS_PATTERN.fullmatch(run_as) is None
        or builder.get("network") != "none"
        or not isinstance(argv, list)
        or not argv
        or not all(
            isinstance(value, str)
            and bool(value)
            and "\n" not in value
            and "\x00" not in value
            for value in argv
        )
    ):
        return [
            "echo 'isolated builder configuration is invalid; refusing to execute upstream code' >&2",
            "exit 1",
        ]
    image_ref = f"{image}@sha256:{digest}"
    command = " ".join(shlex.quote(value) for value in argv)
    return [
        "install -d -m 0777 dist",
        f"docker pull {shlex.quote(image_ref)}",
        (
            "docker run --rm --network none --read-only --cap-drop ALL "
            "--security-opt no-new-privileges --pids-limit 256 --memory 2g "
            f"--cpus 2 --user {shlex.quote(run_as)} "
            '-e HOME=/tmp/home -v "$GITHUB_WORKSPACE:/src:ro" '
            '-v "$GITHUB_WORKSPACE/dist:/out:rw" '
            "--tmpfs /tmp:rw,noexec,nosuid,size=1g "
            f"{shlex.quote(image_ref)} {command}"
        ),
    ]


def lineage_is_valid(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    source = value.get("source_full_name")
    upstream_ref = value.get("upstream_ref")
    return bool(
        isinstance(source, str)
        and REPOSITORY_PATTERN.fullmatch(source) is not None
        and all(part not in {".", ".."} for part in source.split("/"))
        and isinstance(upstream_ref, str)
        and len(upstream_ref) == 40
        and all(character in "0123456789abcdef" for character in upstream_ref)
    )


def indent_commands(lines: list[str], spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" for line in lines)


def indent_text(value: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" for line in value.splitlines())


def write_text_confined(
    root: Path,
    relative_path: str,
    content: str,
    *,
    force: bool,
) -> None:
    parts = PurePosixPath(relative_path).parts
    directory_flags = os.O_RDONLY | os.O_DIRECTORY
    if hasattr(os, "O_NOFOLLOW"):
        directory_flags |= os.O_NOFOLLOW
    root_fd = os.open(root, directory_flags)
    directory_fd = root_fd
    temporary_name: str | None = None
    try:
        for part in parts[:-1]:
            try:
                os.mkdir(part, mode=0o755, dir_fd=directory_fd)
            except FileExistsError:
                pass
            next_fd = os.open(part, directory_flags, dir_fd=directory_fd)
            if directory_fd != root_fd:
                os.close(directory_fd)
            directory_fd = next_fd

        temporary_name = f".{parts[-1]}.{uuid.uuid4().hex}.tmp"
        temporary_flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_NOFOLLOW"):
            temporary_flags |= os.O_NOFOLLOW
        temporary_fd = os.open(
            temporary_name,
            temporary_flags,
            0o644,
            dir_fd=directory_fd,
        )
        try:
            with os.fdopen(
                temporary_fd, "w", encoding="utf-8", closefd=False
            ) as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
        finally:
            os.close(temporary_fd)

        if force:
            os.replace(
                temporary_name,
                parts[-1],
                src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd,
            )
        else:
            os.link(
                temporary_name,
                parts[-1],
                src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd,
                follow_symlinks=False,
            )
            os.unlink(temporary_name, dir_fd=directory_fd)
        os.fsync(directory_fd)
        temporary_name = None
    except OSError as exc:
        if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
            raise ValueError(
                "Release workflow path traverses a symlink or non-directory"
            ) from exc
        raise
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name, dir_fd=directory_fd)
            except FileNotFoundError:
                pass
        if directory_fd != root_fd:
            os.close(directory_fd)
        os.close(root_fd)
